### ISSUE TITLE
Is it perfect for production?

### ISSUE THREAD

**Issue by lidbas** [c0deltin/duckdb-driver#1]
Is it perfect for production?

**Comment by c0deltin** [comment]
Hi @lidbas , I've didn't updated the package for a long time and also never implemented Unittests.
Also not every feature of duckdb is supported yet (see README).
So of course there could be any risk when using it in production. 

May take a look into the current forks of my repo:
[beswarm/duckdb-driver](https://github.com/beswarm/duckdb-driver)
[championswimmer/duckdb-driver](https://github.com/championswimmer/duckdb-driver)
[jedhu0/duckdb-driver](https://github.com/jedhu0/duckdb-driver)
